### ISSUE TITLE
Upgrade to operator-sdk v1.25.0

### ISSUE THREAD

**Issue by nakamasato** [nakamasato/memcached-operator#32]
## error 1 
```
KUBEBUILDER_ASSETS="/Users/m.naka/repos/nakamasato/memcached-operator/bin/k8s/1.25.0-darwin-arm64" go test ./... -coverprofile cover.out
?   	github.com/example/memcached-operator	[no test files]
?   	github.com/example/memcached-operator/api/v1alpha1	[no test files]
/var/folders/c2/hjlk2kcn63s4kds9k2_ctdhc0000gp/T/go-build2430209966/b677/controllers.test flag redefined: ginkgo.seed
panic: /var/folders/c2/hjlk2kcn63s4kds9k2_ctdhc0000gp/T/go-build2430209966/b677/controllers.test flag redefined: ginkgo.seed

goroutine 1 [running]:
flag.(*FlagSet).Var(0x14000122120, {0x10566ddf0, 0x1062771a0}, {0x140001244c0, 0xb}, {0x1050ea45f, 0x2a})
	/Users/m.naka/.gvm/gos/go1.19/src/flag/flag.go:980 +0x2a4
flag.(*FlagSet).Int64Var(...)
	/Users/m.naka/.gvm/gos/go1.19/src/flag/flag.go:767
github.com/onsi/ginkgo/v2/types.bindFlagSet({{0x140001bca00, 0x20, 0x21}, {0x105471620, 0x14000404930}, {0x106248600, 0xd, 0xd}, {{0x0, 0x0}, ...}, ...}, ...)
	/Users/m.naka/.gvm/pkgsets/go1.19/global/pkg/mod/github.com/onsi/ginkgo/v2@v2.1.4/types/flags.go:161 +0x5a4
github.com/onsi/ginkgo/v2/types.NewAttachedGinkgoFlagSet(...)
	/Users/m.naka/.gvm/pkgsets/go1.19/global/pkg/mod/github.com/onsi/ginkgo/v2@v2.1.4/types/flags.go:113
github.com/onsi/ginkgo/v2/types.BuildTestSuiteFlagSet(0x1062771a0, 0x1062768c0)
	/Users/m.naka/.gvm/pkgsets/go1.19/global/pkg/mod/github.com/onsi/ginkgo/v2@v2.1.4/types/config.go:346 +0x4a4
github.com/onsi/ginkgo/v2.init.0()
	/Users/m.naka/.gvm/pkgsets/go1.19/global/pkg/mod/github.com/onsi/ginkgo/v2@v2.1.4/core_dsl.go:47 +0x48
FAIL	github.com/example/memcached-operator/controllers	0.455s
FAIL
make: *** [test] Error 1
```

`}, 60)` -> changed -> fix .upgrade-version.sh

## error 2: `Killed: 9`

```
make kustomize
test -s /Users/m.naka/repos/nakamasato/memcached-operator/bin/kustomize || { curl -Ss "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash -s -- 3.8.7 /Users/m.naka/repos/nakamasato/memcached-operator/bin; }
make: *** [/Users/m.naka/repos/nakamasato/memcached-operator/bin/kustomize] Killed: 9
```

**Comment by nakamasato** [comment]
#33
